config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :schedules
  get 'contact/new'

  get 'contact/create'

  resources :internships
  get 'home/index'
  get 'schedules/index'
  get 'internships/index'
  get 'requirements/index'

  root 'home#index'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/internship.rb
class Internship < ApplicationRecord
	geocoded_by :address
	after_validation :geocode

	mount_uploader :image, ImageUploader
	mount_uploader :carouselImage1, ImageUploader
	mount_uploader :carouselImage2, ImageUploader
	mount_uploader :carouselImage3, ImageUploader
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_format_of :email, with: /\@depauw\.edu/, message: 'You must be a DePauw student to access this website'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/internships_controller.rb
class InternshipsController < ApplicationController
  before_action :set_internship, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /internships
  # GET /internships.json
  

  def index
    @internships = Internship.all
    
    @internship_properties = Array.new
    @internships.each do |internship|
      @internship_properties.push(internship)
    end

   
    @hash = Gmaps4rails.build_markers(@internship_properties) do |internship_prop, marker|
      #concat_info_window = "Name: #{internship_prop.name}, Location: #{internship_prop.address}, Company: #{internship_prop.company}, Role: #{internship_prop.title}, Date: #{internship_prop.date}, Description: #{internship_prop.description}"
      marker.lat internship_prop.latitude
      marker.lng internship_prop.longitude
    
      #marker.infowindow concat_info_window 
      marker.infowindow render_to_string(:partial => "/internships/info", :locals => { :internship => @internship, :internship_prop => internship_prop.company, :internship_prop2 => internship_prop.name})

    end
  end



  # GET /internships/1
  # GET /internships/1.json
  def show
    
  end

  # GET /internships/new
  def new
    @internship = Internship.new
  end

  # GET /internships/1/edit
  def edit
  end

  # POST /internships
  # POST /internships.json
  def create
    @internship = Internship.new(internship_params)

    respond_to do |format|
      if @internship.save
        format.html { redirect_to @internship, notice: 'Internship was successfully created.' }
        format.json { render :show, status: :created, location: @internship }
      else
        format.html { render :new }
        format.json { render json: @internship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /internships/1
  # PATCH/PUT /internships/1.json
  def update
    respond_to do |format|
      if @internship.update(internship_params)
        format.html { redirect_to @internship, notice: 'Internship was successfully updated.' }
        format.json { render :show, status: :ok, location: @internship }
      else
        format.html { render :edit }
        format.json { render json: @internship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /internships/1
  # DELETE /internships/1.json
  def destroy
    @internship.destroy
    respond_to do |format|
      format.html { redirect_to internships_url, notice: 'Internship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_internship
      @internship = Internship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def internship_params
      params.require(:internship).permit(:latitude, :longitude, :address, :name, :location, :title, :company, :date, :description, :image, :remove_image, :carouselImage1, :remove_carouselImage1, :carouselImage2, :remove_carouselImage2, :carouselImage3, :remove_carouselImage3)
    end
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
	  before_action :authenticate_user!
	def index
	end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  #this before action is needed if we want all users to login
  #before_action :authenticate_user!
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.group(:studentId).count


    
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:name, :studentId, :eventName, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/internships_helper.rb
module InternshipsHelper
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/internships/_form.html.erb
<%= form_for(internship) do |f| %>
  <% if internship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(internship.errors.count, "error") %> prohibited this internship from being saved:</h2>

      <ul>
      <% internship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %> 
    <% end %>
  </div>

  <div class="field">
    <%= f.label :carouselImage1 %>
    <%= f.file_field :carouselImage1 %>
    <% if f.object.carouselImage1? %>
      <%= image_tag f.object.carouselImage1.url %>
      <%= f.label :remove_carouselImage1 %>
      <%= f.check_box :remove_carouselImage1 %> 
    <% end %>
  </div>

    <div class="field">
    <%= f.label :carouselImage2 %>
    <%= f.file_field :carouselImage2 %>
    <% if f.object.carouselImage2? %>
      <%= image_tag f.object.carouselImage2.url %>
      <%= f.label :remove_carouselImage2 %>
      <%= f.check_box :remove_carouselImage2 %> 
    <% end %>
  </div>

  <div class="field">
    <%= f.label :carouselImage3 %>
    <%= f.file_field :carouselImage3 %>
    <% if f.object.carouselImage3? %>
      <%= image_tag f.object.carouselImage3.url %>
      <%= f.label :remove_carouselImage3 %>
      <%= f.check_box :remove_carouselImage3 %> 
    <% end %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/internships/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Internships</title>  
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <script src="//maps.google.com/maps/api/js?key=AIzaSyBj4qLUeW291Z5WvVOwzseQONRBGCnA8ds"></script>
      <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
      <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  </head>

<body>

<h1>Editing Internship</h1>

<%= render 'form', internship: @internship %>

<%= link_to 'Show', @internship %> |
<%= link_to 'Back', internships_path %>


</body>
</html>

app/views/internships/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Internships</title>  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyBj4qLUeW291Z5WvVOwzseQONRBGCnA8ds"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
</head>

<body class = "body">
    <div class = "container">
       <div class = "row">
          <div class = "col-md-12">
            <h1 class = "InternshipHead"> Internship Map </h1>
            <p class = "InternshipDes"> Each pin shows information about different Media Fellows internships. Click around to explore different internship opportunities and learn more details about specific internships! </p>
            <p class = "InternshipNote"> NOTE: Due to a Google Maps issue, page may need to be refreashed or zoomed in order for the map or pins to load. </p>
        </div>
    </div>

    <!-- Generates map -->
    <div style='width: 800px;'>
        <div id="map" style='width: 1100px; height: 600px'></div>
    </div>


    <!--
    <script type="text/javascript">
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    </script>



-->


<!-- to turn clustering off, inside the marker:{} paramater add: {Markers: {clusterer: undefined}}); -->

    <!--, {markers:
        {clusterer: {
            gridSize: 40,
            maxZoom: 25,
            styles:[{
                textSize: 1,
                textColor: '#000000',
                url: '/assets/darkLocation.png',
                height: 56,
                width: 50},
                {
                    textSize: 1,
                    textColor: '#000000',
                    url: '/assets/darkLocation.png',
                    height: 66,
                    width: 60},
                    {
                        textSize: 1,
                        textColor: '#000000',
                        url: '/assets/darkLocation.png',
                        height: 76,
                        width: 70}
                        ]} }} -->
                        <script type="text/javascript">
                        handler = Gmaps.build('Google', {markers: 
                            {clusterer: 
                                {gridSize: 40, maxZoom: 11,
                                    styles:[{
                                        textSize: 1,
                                        textColor: '#000000',
                                        url: '/assets/darkLocation.png',
                                        height: 56,
                                        width:50
                                    }]
                                }}}



                                );



                        handler.buildMap({ provider: {styles:[
                            {
                                "featureType": "all",
                                "elementType": "geometry",
                                "stylers": [
                                {
                                    "color": "#11151b"
                                }
                                ]
                            },
                            {
                                "featureType": "all",
                                "elementType": "labels.text.fill",
                                "stylers": [
                                {
                                    "gamma": 0.01
                                },
                                {
                                    "lightness": 20
                                }
                                ]
                            },
                            {
                                "featureType": "all",
                                "elementType": "labels.text.stroke",
                                "stylers": [
                                {
                                    "saturation": -31
                                },
                                {
                                    "lightness": -33
                                },
                                {
                                    "weight": 2
                                },
                                {
                                    "gamma": 0.8
                                }
                                ]
                            },
                            {
                                "featureType": "all",
                                "elementType": "labels.icon",
                                "stylers": [
                                {
                                    "visibility": "off"
                                }
                                ]
                            },
                            {
                                "featureType": "administrative",
                                "elementType": "labels.text",
                                "stylers": [
                                {
                                    "lightness": "100"
                                }
                                ]
                            },
                            {
                                "featureType": "administrative",
                                "elementType": "labels.text.stroke",
                                "stylers": [
                                {
                                    "weight": "1.58"
                                },
                                {
                                    "saturation": "6"
                                },
                                {
                                    "color": "#8a8181"
                                }
                                ]
                            },
                            {
                                "featureType": "landscape",
                                "elementType": "geometry",
                                "stylers": [
                                {
                                    "lightness": 30
                                },
                                {
                                    "saturation": 30
                                }
                                ]
                            },
                            {
                                "featureType": "poi",
                                "elementType": "geometry",
                                "stylers": [
                                {
                                    "saturation": 20
                                }
                                ]
                            },
                            {
                                "featureType": "poi.attraction",
                                "elementType": "labels.text",
                                "stylers": [
                                {
                                    "lightness": "60"
                                }
                                ]
                            },
                            {
                                "featureType": "poi.park",
                                "elementType": "geometry",
                                "stylers": [
                                {
                                    "lightness": 20
                                },
                                {
                                    "saturation": -20
                                }
                                ]
                            },
                            {
                                "featureType": "poi.park",
                                "elementType": "labels.text",
                                "stylers": [
                                {
                                    "lightness": "29"
                                }
                                ]
                            },
                            {
                                "featureType": "road",
                                "elementType": "geometry",
                                "stylers": [
                                {
                                    "lightness": 10
                                },
                                {
                                    "saturation": -30
                                }
                                ]
                            },
                            {
                                "featureType": "road",
                                "elementType": "geometry.stroke",
                                "stylers": [
                                {
                                    "saturation": 25
                                },
                                {
                                    "lightness": 25
                                }
                                ]
                            },
                            {
                                "featureType": "water",
                                "elementType": "all",
                                "stylers": [
                                {
                                    "lightness": -20
                                }
                                ]
                            },
                            {
                                "featureType": "water",
                                "elementType": "geometry.fill",
                                "stylers": [
                                {
                                    "color": "#000000"
                                }
                                ]
                            },
                            {
                                "featureType": "water",
                                "elementType": "labels.text",
                                "stylers": [
                                {
                                    "lightness": "29"
                                }
                                ]
                            }
                            ]}, internal: {id: 'map'}}, function initialize(){
                              markers = handler.addMarkers(<%=raw @hash.to_json %>);
                              handler.bounds.extendWith(markers);
                              handler.fitMapToBounds(); 

                              google.maps.event.addDomListener(window, "load", initialize);
                          });
</script>



<br>
<br>
<br>


    <!--


    <div class="page-header">
      <%=link_to new_internship_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Internship
      <%end%>
      <h1>Listing Internships</h1>
    </div>

    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
          <th>Latitude</th>
          <th>Longitude</th>
          <th>Address</th>
          <th>Name</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>


      <tbody>
        <%=content_tag_for(:tr, @internships) do |internship| %>
          <tr>
            <td><%= internship.latitude %></td>
            <td><%= internship.longitude %></td>
            <td><%= internship.address %></td>
            <td><%= internship.name %></td>
            <td><%= link_to 'Show', internship %></td>
            <td><%= link_to 'Edit', edit_internship_path(internship) %></td>
            <td><%= link_to 'Destroy', internship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>

-->



</div>

</body>
</html>

app/views/internships/new.html.erb
<h1>New Internship</h1>

<%= render 'form', internship: @internship %>

<%= link_to 'Back', internships_path %>

app/views/internships/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Internships</title>  
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <script src="//maps.google.com/maps/api/js?key=AIzaSyBj4qLUeW291Z5WvVOwzseQONRBGCnA8ds"></script>
      <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
      <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  </head>

<body>


<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @internship.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @internship.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @internship.address %>
</p>

<p>
  <strong>Name:</strong>
  <%= @internship.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @internship.location %>
</p>

<p>
  <strong>Title:</strong>
  <%= @internship.title %>
</p>

<p>
  <strong>Company:</strong>
  <%= @internship.company %>
</p>

<p>
  <strong>Date:</strong>
  <%= @internship.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @internship.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @internship.image.url unless @internship.image.blank? %>
</p>

<p>
  <strong>carouselImage1:</strong>
  <%= image_tag @internship.carouselImage1.url unless @internship.carouselImage1.blank? %>
</p>
<p>
  <strong>carouselImage2:</strong>
  <%= image_tag @internship.carouselImage2.url unless @internship.carouselImage2.blank? %>
</p>

<p>
  <strong>carouselImage3:</strong>
  <%= image_tag @internship.carouselImage3.url unless @internship.carouselImage3.blank? %>
</p>



<%= link_to 'Edit', edit_internship_path(@internship) %> |
<%= link_to 'Back', internships_path %>

</body>
</html>

app/views/schedules/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>MediaSeminar</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	
</head>
<body class = "showForm">
	<div class = "container">
		<div class = "row">
			<div class = "col-md-8">
				<h1>Editing Schedule</h1>
			</div>
		</div>

		<div class = "row">
			<div class = "col-md-4">
				<%= render 'form', schedule: @schedule %>
			</div>
		</div>

		<div class = "row">
			<div class = "col-md-4">

				<%= link_to 'Show', @schedule %> |
				<%= link_to 'Back', schedules_path %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/schedules/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediaSeminar</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body class = "speakerBody">
  <div class = "container">
    <div class = "headLog">
      <div class = "row">
        <div class = "col-md-12">
          <h1>Speaker Series</h1>

          <%=link_to new_schedule_path, class: 'btn btn-sample btn-large' do %>
          <span class="glyphicon glyphicon-plus"></span>
          Log Attendance at Speaker Credit

          <%end%>
        </div>
      </div>
    </div>
    <hr>
    <div class = "row">
      <div class = "col-md-12">
        <div class = "calStyles">
          <iframe src="https://calendar.google.com/calendar/embed?src=depauw.edu_jopjs7ge988ihoeu4uj0mi5fs8%40group.calendar.google.com&ctz=America/New_York" style="border: 0" width="1100" height="600" frameborder="0" scrolling="no" align="middle"></iframe>
        </div>
      </div>
    </div>
    <hr>

    <div class = "row">
      <div class = "col-md-12">

        <div class = "headLog2">
          <h2>Speaker Credit</h2>
        </div>
        <div class="tableStyle container container-fluid">
          <table class="table table-striped">
            <thead>
              <tr>
                <th class="tableHead">[Student ID, Events Attended]</th>
              </tr>
            </thead>

            <tbody>
              <% @schedules.each do |schedule| %>
              <tr>
                <td><%=schedule%></td>


              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div>

      <br>

    </div>
  </body>
  </html>

app/views/schedules/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>MediaSeminar</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body class = "signInForm">
	<div class = "container">
		<div class = "signInForm">
		<div class = "logingShow">

			<div class = "row">
				<div class = "col-md-8">
					<h1>Log Speaker Credit Attendence</h1>
				</div>
			</div>
			<div class = "row">
				<div class = "col-md-8">
					<%= render 'form', schedule: @schedule %>

					<%= link_to 'Back', schedules_path %>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

app/views/schedules/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediaSeminar</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body class = "showForm">
  <div class = "container">

    <div class = "row">
        <div class = "col-md-8">
          <p>
            <strong>name:</strong>
            <%= @schedule.name %>
          </p>
        </div>
      </div>

      <div class = "row">
        <div class = "col-md-8">
          <p>
            <strong>Student ID:</strong>
            <%= @schedule.studentId %>
          </p>
        </div>
      </div>

      <div class = "row">
        <div class = "col-md-8">
          <p>
            <strong>Event Name:</strong>
            <%= @schedule.eventName %>
          </p>
        </div>
      </div>

      <div class = "row">
        <div class = "col-md-8">
          <p>
            <strong>Description:</strong>
            <%= @schedule.description %>
          </p>
        </div>
      </div>
      <div class = "row">
        <div class = "col-md-8">
          <%= link_to 'Edit', edit_schedule_path(@schedule) %> |
          <%= link_to 'Back', schedules_path %>
        </div>
      </div>   
  </div>
</body>
</html>